arm:
 type: ur10
sensors:
 logical_camera_bin_1_2:
   type: logical_camera
   pose:
     xyz: [-0.457372, -1.325077, 1.474698]
     rpy: [0, 'pi/2', 'pi/2']

 logical_camera_bin_5_6:
   type: logical_camera
   pose:
     xyz: [-0.457372, -0.53557, 1.474698]
     rpy: [0, 'pi/2', 'pi/2']

 logical_camera_bin_6_7:
   type: logical_camera
   pose:
     xyz: [-0.457372, 0.230893, 1.474698]
     rpy: [0, 'pi/2', 'pi/2']

 logical_camera_bin_7_8:
   type: logical_camera
   pose:
     xyz: [-0.457372, 1.003074, 1.474698]
     rpy: [0, 'pi/2', 'pi/2']

 logical_camera_agv_1:
   type: logical_camera
   pose:
     xyz: [0.3, 3.15, 1.5]
     rpy: [0, 'pi/2', 0]
 logical_camera_agv_2:
   type: logical_camera
   pose:
     xyz: [0.3, -3.15, 1.5]
     rpy: [0, 'pi/2', 0]
 logical_camera_belt_1:
   type: logical_camera
   pose:
     xyz: [1.217532, 1.754701, 1.648080]
     rpy: [0, 'pi/2', 0]