arm:
 type: ur10
sensors:
 # break_beam_1:
 #   type: break_beam
 #   pose:
 #     xyz: [1.6, 2.25, 0.91]
 #     rpy: [0, 0, 'pi']
 # proximity_sensor_1:
 #   type: proximity_sensor
 #   pose:
 #     xyz: [0.95, 2.6, 0.916]
 #     rpy: [0, 0, 0]

 logical_camera_bin_1_2:
   type: logical_camera
   pose:
     xyz: [-1, -1.12, 1.474698]
     rpy: [0, 'pi/2', 0]

 logical_camera_bin_2_3:
   type: logical_camera
   pose:
     xyz: [-1, -0.163713, 1.474698]
     rpy: [0, 'pi/2', 0]

 logical_camera_bin_3_4:
   type: logical_camera
   pose:
     xyz: [-1, 0.78, 1.474698]
     rpy: [0, 'pi/2', 0]

 logical_camera_bin_5_6:
   type: logical_camera
   pose:
     xyz: [-0.343639, -1.12, 1.474698]
     rpy: [0, 'pi/2', 0]

 logical_camera_bin_6_7:
   type: logical_camera
   pose:
     xyz: [-0.343639, -0.163713, 1.474698]
     rpy: [0, 'pi/2', 0]

 logical_camera_bin_7_8:
   type: logical_camera
   pose:
     xyz: [-0.343639, 0.78, 1.474698]
     rpy: [0, 'pi/2', 0]

 logical_camera_agv_1:
   type: logical_camera
   pose:
     xyz: [0.3, 3.15, 1.5]
     rpy: [0, 'pi/2', 0]
 logical_camera_agv_2:
   type: logical_camera
   pose:
     xyz: [0.3, -3.15, 1.5]
     rpy: [0, 'pi/2', 0]
 logical_camera_belt_1:
   type: logical_camera
   pose:
     xyz: [1.217532, 1.754701, 1.648080]
     rpy: [0, 'pi/2', 0]
 # laser_profiler_1:
 #   type: laser_profiler
 #   pose:
 #     xyz: [1.21, 4, 1.64]
 #     rpy: ['-pi', 'pi/2', 'pi/2']